config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/home'
root 'static_pages#home'

  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def show
    @people = Person.find(params[:id])
  end

  def new
    @people = Person.new
  end

  def create
    @people = Person.new(page_params)

    if @people.save
      redirect_to people_path
    else
      render :new
  end
end

def edit
  @people = Person.find(params[:id])
end

def update
 @people = Person.find(params[:id])

 if @people.update(page_params)
  redirect_to people_path
 else
  render :edit
 end
end

def destroy
  Person.find(params[:id]).destroy
  redirect_to people_path
end


private 
def page_params
  params.require(:person).permit(:name, :age, :hair_color, :eye_color, :gender, :alive)
end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navbar.html.erb
<link rel="stylesheet" type="text/css" href="people.scss">
<ul>

<li><a><%= link_to 'Home', root_path %></a></li>
<li><a><%= link_to 'New Person', new_person_path %></a></li>
<li><a><%= link_to 'People', people_path %></a></li>

</ul>


<style>


</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PeopleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/people/edit.html.erb
<h1>Edit Person</h1>
<div id="edit-form">
<%= form_for @people do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :age %>
  <%= f.text_field :age %>

  <%= f.label :hair_color %>
  <%= f.text_area :hair_color %>
  
   <%= f.label :eye_color %>
  <%= f.text_area :eye_color %>
  
    <%= f.label :gender %>
  <%= f.text_area :gender %>

   <%= f.label :alive %>
  <%= f.text_area :alive %>

  <%= f.submit %>
<% end %>
</div>

<style>
#edit-form {
  display: flex;
  flex-direction: column;
  flex-wrap: wrap;
  width: 500px;
  
}
</style>

app/views/people/index.html.erb
<link rel="stylesheet" type="text/css" href="people.scss">
<h1 id="title"> People </h1>
<% @people.each do |person| %>
  <h2><%= person.name %></h2>
  <div id="options-bar">
  <%= link_to 'Show ', person_path(person) %>
  <%= link_to 'New ', new_person_path %>
 <%= link_to "Edit ", edit_person_path(person) %>
 <%= link_to "Delete ", person, method: :delete %>
 </div>
<% end %>

app/views/people/new.html.erb
<h1>New Person</h1>
<div id="new-form">
<%= form_for @people do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
 <br />
  <%= f.label :age %>
  <%= f.text_field :age %>
<br />
  <%= f.label :hair_color %>
  <%= f.text_area :hair_color %>
  <br />
  <%= f.label :eye_color %>
  <%= f.text_area :eye_color %>
<br />
  <%= f.label :gender %>
  <%= f.text_area :gender %>
  <br />
  <%= f.label :alive %>
  <%= f.text_area :alive %>
<br />
  <%= f.submit %>
<% end %>
</div>

<style>
#new-form {
  display: flex;
  flex-direction: column;
  flex-wrap: wrap;
  width: 500px;
  
}
</style>

app/views/people/show.html.erb
<div id="profile-page">
<h1>Name: <%= @people.name %></h1>
<h4>Age: <%= @people.age %></h1>
<p>Eye Color: <%= @people.eye_color %></p>
<p>Hair Color: <%= @people.hair_color %></p>
<p>Gender: <%= @people.gender %></p>
<p>Living: <%= @people.alive %></p>
</div>
<%= link_to 'Back', people_path %>



<style>
#profile-page {
  display: flex;
  flex-direction: column;
  font-family: helvetica;
  font-size: 24px;
}

</style>

app/views/static_pages/home.html.erb
<h1>This is my amazing app to keep track of people</h1>
<p>Follow any links on the top menu to explore what you can do</p>

<style>
h1 {
  display: flex;
  justify-content: center;
  font-family: helvetica;
}
p {
}
</style>